language: php

php:
  - '7.3'
  - '7.4'

install: [
  "mkdir -p app/etc var",
  "echo \"{\\\"http-basic\\\":{\\\"repo.magento.com\\\":{\\\"username\\\":\\\"${MAGENTO_USERNAME}\\\",\\\"password\\\":\\\"${MAGENTO_PASSWORD}\\\"}}}\" > auth.json",
  "composer install --prefer-dist"
]

before_install:
  - composer self-update --1
  - composer --version
after_install:
  - composer require --dev magento/magento-coding-standard

cache:
  directories:
    - $HOME/.composer/cache

script:
  - vendor/bin/phpcs --config-set installed_paths vendor/magento/magento-coding-standard/
  - vendor/bin/phpcs --standard=vendor/magento/magento-coding-standard/Magento2 --ignore=vendor,pub ./